correções

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,7 +60,7 @@ jobs:
   package:
     name: Package Report
     runs-on: ubuntu-latest
-    needs: test
+    needs: [validate, test]
     outputs:
       artifact_path: report.zip
     steps:
@@ -101,14 +101,15 @@ jobs:
     name: Deploy
     runs-on: ubuntu-latest
     needs: package
+    if: github.event_name == 'workflow_dispatch'
     environment:
       name: production
     steps:
       - name: Validar variável obrigatória
         run: |
           if [ -z "${{ github.event.inputs.DEPLOY_ENV }}" ]; then
-            echo "::error::Variável DEPLOY_ENV não definida. Abortando."
-            exit 1
+          echo "::error::Variável DEPLOY_ENV não fornecida via execução manual."
+          exit 1
           fi
           echo "::notice::Deploy autorizado para o ambiente ${{ github.event.inputs.DEPLOY_ENV }}"
 
